version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - npm install

  build:
    commands:
      - echo Build step (no compilation needed)

  post_build:
    commands:
      - echo Node.js app is ready
artifacts:
  files:
    - '**/*'
